Update gdb-oneapi to 2024.0

diff --git a/.github/workflows/conda-package.yml b/.github/workflows/conda-package.yml
--- a/.github/workflows/conda-package.yml
+++ b/.github/workflows/conda-package.yml
@@ -254,9 +254,10 @@ jobs:
       - name: Run gdb tests
         if: ${{ matrix.scope == 'gdb' }}
         env:
-          GDB_URL: https://registrationcenter-download.intel.com/akdlm/IRC_NAS/fcea1bcd-6a63-4849-b304-906ff71dc2c0/l_dpcpp_dbg_p_2023.2.0.49333_offline.sh
-          GDB_INSTALLER: l_dpcpp_dbg_p_2023.2.0.49333_offline.sh
+          GDB_URL: https://registrationcenter-download.intel.com/akdlm/IRC_NAS/afb921d3-c9e7-4610-b3a9-725c77a87cf4/l_dpcpp_dbg_p_2024.0.0.49350_offline.sh
+          GDB_INSTALLER: l_dpcpp_dbg_p_2024.0.0.49350_offline.sh
         run: |
+          conda install intel::dpcpp_linux-64
           conda install pexpect
           wget -nc -q ${{ env.GDB_URL }}
           chmod +x ${{ env.GDB_INSTALLER }}
@@ -264,6 +265,12 @@ jobs:
           export ONEAPI_ROOT=/tmp/gdb
           ./${{ env.GDB_INSTALLER }} -a -s --eula accept --install-dir $ONEAPI_ROOT
           source $ONEAPI_ROOT/debugger/latest/env/vars.sh
+          gdb_version=$(echo "$GDB_INSTALLER" | grep -oP '\d+\.\d+' | head -n 1)
+          icpx_version=$(icpx --version | head -n 1 | awk '{print $NF}' | cut -c 2-7)
+          if [ "$gdb_version" != "$icpx_version" ]; then
+            echo "Error: GDB version ($gdb_version) does not match icpx version ($icpx_version)"
+            exit 1
+          fi
           pytest -q -ra --disable-warnings --pyargs ${{ env.MODULE_NAME }}.tests.debugging -vv
 
   upload_anaconda:
